[package]
name = "wasm-bindings"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
adnl = { path = ".." }
wasm-bindgen = "0.2.79"

[profile.release]
opt-level = 's'
lto = true