[package]
name = "adnl-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
adnl = { path = "..", features = ["alloc"] }
wasm-bindgen = "0.2.79"
js-sys = "0.3.56"
ciborium-io = "0.2.0"

[profile.release]
opt-level = 's'
lto = true